### ISSUE TITLE
train.py

### ISSUE THREAD

**Issue by birdsmart** [YAndrewL/CLAPE#2]
Hello, I am very interested in your paper, I want to use this model to do more, can you upload the training file for reference and learning, thank you very much

**Comment by YAndrewL** [comment]
> Hello, I am very interested in your paper, I want to use this model to do more, can you upload the training file for reference and learning, thank you very much

Thanks for your interest in our work, please check [CLAPE-SMB](https://github.com/JueWangTHU/CLAPE-SMB) repo for the training process and contact with [wangjue21@mails.tsinghua.edu.cn](mailto:wangjue21@mails.tsinghua.edu.cn) if you have further questions in training.
